### ISSUE TITLE
allow callbacks to make this a giant polyfill?

### ISSUE THREAD

**Issue by jonathanong** [normalize/mz#12]
since we have node and io.js now, i'm thinking of a library that normalizes both as much as possible. an example is https://github.com/normalize/mz/issues/11. we should add callbacks back and always return promises so people can __always__ use `mz` vs. only for promises. 

/cc @dougwilson @dead-horse

**Comment by dougwilson** [comment]
The trick would of course be how to even emulate access in Node.js, since it's core is permission checking, not really a rename of exists.

**Comment by timoxley** [comment]
@dougwilson just wrap up the `fs.stat` interface. I'm wondering if a binary extension could work better so you don't lose the `fs.access` speedup over `fs.stat`.

**Comment by dougwilson** [comment]
It just sounds like a lot of work; you have to check the uid and gid of the process to the file and consider the mode. Then you have the sticky bit and how it changes how those comparisons work (and the meaning of the sticky bit differs by OS).

**Comment by dougwilson** [comment]
And just as a disclaimer I have not really read the fs.access API beyond just that it is used to determine what types of access the process has to a given file.

**Comment by jonathanong** [comment]
done
