### ISSUE TITLE
Don't use native-or-bluebird

### ISSUE THREAD

**Issue by RangerMauve** [normalize/mz#16]
Not every project will want to rely on all of Bluebird, so [any-promise](https://www.npmjs.com/package/any-promise) allows for any one of the most popular promise polyfills and libraries to be installed.

**Comment by rstacruz** [comment]
:+1: this is perfect. want a PR?

**Comment by targos** [comment]
-1
If you have a library in your dependency tree that uses one of those Promise modules, with npm 3 it will be installed at the root of `node_modules` and would then be loaded by `any-promise`.

**Comment by LinusU** [comment]
When is 0.12 support ending? Maybe it's time to drop anything else than the built-in promise?

**Comment by coderhaoxin** [comment]
> Maybe it's time to drop anything else than the built-in promise

:+1:

**Comment by rstacruz** [comment]
I'm okay with doing that now. If anyone runs into trouble, they can always:

```js
global.Promise = require('bluebird')
```

**Comment by rstacruz** [comment]
> If you have a library in your dependency tree that uses one of those Promise modules, with npm 3 it will be installed at the root of node_modules and would then be loaded by any-promise.

I'm not really sure this is a problem.

```js
var Promise = global.Promise || require('any-promise')
```

It'll always load the globally-defined `Promise` for those on Node 4+.

**Comment by targos** [comment]
@rstacruz true. I wouldn't mind this approach.

**Comment by LinusU** [comment]
@rstacruz That will load the broken promise support on Node v0.11.13+

**Comment by ashaffer** [comment]
+1 on this. Right now it *defaults* to bluebird, which means that the behavior of this package is non-deterministic with respect to which other packages happen to be installed (including dependencies of your other dependencies in npm 3). This is terrible behavior.

**Comment by LinusU** [comment]
I agree that defaulting to bluebird is bad. Also, bluebird tries to do more than just be a promise, which means that a developer can come to rely on the returned promise being a blurbird promise. Some things we could do in order of my personal preference:

1. Drop support for older platforms and only use builtin `Promise`
1. Subclass `Promise` and fix the bug on older platforms
1. Require `es6-promise` on older platforms
1. Always use `es6-promise`
1. Always use `bluebird`

**Comment by RangerMauve** [comment]
Personally, I like option 1 the most, if people want to use older platforms they can just use a polyfill like [native-promise-only](https://github.com/getify/native-promise-only)

**Comment by RangerMauve** [comment]
Have the [recent changes](https://github.com/kevinbeaty/any-promise/issues/1) in any-promise made it more appealing to integrate?

**Comment by jonathanong** [comment]
i've looked at `any-promise`. this is my only issue: https://github.com/kevinbeaty/any-promise/issues/5. other than that, :+1:

**Comment by jonathanong** [comment]
unless you guys don't care about that. then i can switch it and do a major version bump

**Comment by jonathanong** [comment]
ok switching
