### ISSUE TITLE
How to use with single exported functions

### ISSUE THREAD

**Issue by rkmax** [normalize/mz#38]
I found this library and I think it's brilliant. but I have some issues with a library that is just a function [rimraf](https://github.com/isaacs/rimraf)

```js
const rimraf = require('mz/rimraf')
...
Error: Cannot find module 'mz/rimraf'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
```

**Comment by jonathanong** [comment]
just use https://www.npmjs.com/package/thenify or something!

**Comment by LinusU** [comment]
This library is only for the built in modules that ship with Node.js. Everything is hand ported so it wouldn't make sense for it to work with any library...

As said, you'll have to use something like thenify or pify...

**Comment by rkmax** [comment]
Thanks for the clarification @LinusU. I think would be great some explicit note on the readme talking about it

**Comment by LinusU** [comment]
Great idea, care to make a pull request? :)

**Comment by rkmax** [comment]
Sure
