### ISSUE TITLE
net, http and https candidates

### ISSUE THREAD

**Issue by wryk** [normalize/mz#4]
what do you think about :

## net
* [Server#listen](http://nodejs.org/api/net.html#net_server_listen_port_host_backlog_callback)
* [Server#close](http://nodejs.org/api/net.html#net_server_close_callback)
* [Socket#write](http://nodejs.org/api/net.html#net_socket_write_data_encoding_callback)
* [Socket#setTimeout](http://nodejs.org/api/net.html#net_socket_settimeout_timeout_callback)

## http
* [Server#listen](http://nodejs.org/api/http.html#http_server_listen_port_hostname_backlog_callback)
* [Server#close](http://nodejs.org/api/http.html#http_server_close_callback)
* [Server#setTimeout](http://nodejs.org/api/http.html#http_server_settimeout_msecs_callback)
* [ServerResponse#setTimeout](http://nodejs.org/api/http.html#http_response_settimeout_msecs_callback)
* [request](http://nodejs.org/api/http.html#http_http_request_options_callback)
* [get](http://nodejs.org/api/http.html#http_http_get_options_callback)
* [ClientRequest#setTimeout](http://nodejs.org/api/http.html#http_request_settimeout_timeout_callback)

## https
* [Server#listen](http://nodejs.org/api/https.html#https_server_listen_port_host_backlog_callback)
* [Server#close](http://nodejs.org/api/https.html#https_server_close_callback)
* [request](http://nodejs.org/api/https.html#https_https_request_options_callback)
* [get](http://nodejs.org/api/https.html#https_https_get_options_callback)

**Comment by felixfbecker** [comment]
I have one and would love to have this in my tests:
```js
import app from '../api' // a koa app, but could also be an express app whatever
import request from 'request-promise'
describe('api', function () {
  let server
  before(async function () {
    server = http.createServer(app.callback())
    await server.listen(3000)
  })
  describe('/stuff', function () {
    it('should return some stuff', async function () {
      let response = await request('http://localhost:3000/stuff', {simple: false})
      expect(response.statusCode).to.equal(200)
    })
  })
  after(async function () {
    await server.close()
  })
})
```
I like to write in ES7, but it would be the same in ES6:
```js
let app = require('../api') // a koa app, but could also be an express app whatever
let request = require('request-promise')
describe('api', function () {
  let server
  before(function (done) {
    server = http.createServer(app.callback())
    return server.listen(3000)
  })
  describe('/stuff', function () {
    it('should return some stuff', function () {
      return request('http://localhost:3000/stuff', {simple: false}).then(response => {
        expect(response.statusCode).to.equal(200)
      })
    })
  })
  after(function () {
    return server.close()
  })
})
```
It might not seem such a big deal, but this is just an example. I have lots of submodules in my api that are tested independently, so each test sets up their own server. This means I have to close them properly of course after the test is finished so the next test can begin. The logic in my before hooks is also sometimes quite complicated, so I cant just pass the _done_ callback to listen, I have to await other async tasks, which is why I would like to use promises (and mocha has good support for them). Currently I have to promisify with bluebird first.

**Comment by felixfbecker** [comment]
Btw requisition looks slick, I might use it instead of request-promise!

**Comment by felixfbecker** [comment]
I guess it's a bit complicated because thenify-all is not written to thenify prototypes.

**Comment by jonathanong** [comment]
problem with that API is that those prototypes are emitters. promisifying is too opinionated because there are more states than just `pending|success|error`

**Comment by wryk** [comment]
I agree with the last point

@felixfbecker Should I close ? Do you want to add something ?

**Comment by felixfbecker** [comment]
@jonathanong Which of the mentioned functions return event emitters? o.O

**Comment by wryk** [comment]
@felixfbecker Yep, *.Server and net.Socket extends EventEmitter

**Comment by felixfbecker** [comment]
@wryk Sure, but what's wrong with `listen` or `close` returning a promise?

**Comment by LinusU** [comment]
@wryk `.Server` and `.Socket` isn't mentioned in the original proposal.

I think that all the functions that takes a callback should be converted to return a promise. This is a little bit more complicated with classes that gets instantiated, but not at all hard. I [did it with `readline.Interface` by making a subclass called `InterfaceAsPromised` which overrides the desired methods](https://github.com/normalize/mz/blob/master/readline.js).
