### ISSUE TITLE
Add mkdtemp to fs.js

### ISSUE THREAD

**Issue by EvanCarroll** [normalize/mz#40]
[mkdtemp docs](https://nodejs.org/api/fs.html#fs_fs_mkdtemp_prefix_options_callback)

```
fs.mkdtemp(prefix[, options], callback)#
Added in: v5.10.0
```

**Comment by RyanZim** [comment]
Looks like this was fixed in 4dd2cfe.

**Comment by LinusU** [comment]
Thanks
