### ISSUE TITLE
integrating request-promise-native?

### ISSUE THREAD

**Issue by The-Alchemist** [normalize/mz#44]
Would you consider integrating https://github.com/request/request-promise-native?  I can submit a pull request.

**Comment by dead-horse** [comment]
I don't think we would do this, this project is aim to make all the node's native api support promise, `request` does not included.

**Comment by The-Alchemist** [comment]
Ah, I thought ``request`` was official node.  After some research, it appears only ``http`` is.

Would you include a Promise-based PR for at least ``http.get``?

**Comment by dead-horse** [comment]
`http.get` is not user-friendly (that's why developers will write library `request`, `superagent` and so on)
