### ISSUE TITLE
Different output with mz/child_process.exec vs node's child_process.exec

### ISSUE THREAD

**Issue by cloverich** [normalize/mz#54]
When I use `exec` I am getting different output with `mz/child_process` than `child_process`. Example program outputting git tags:

```js
const cp = require('child_process');
const mzcp = require('mz/child_process');


function execPromise(cmd) {
  return new Promise((resolve, reject) => {
    cp.exec(cmd, (err, stdout) => {
      err ? reject(err) : resolve(stdout);
    });
  })
}

async function test(name, exec) {
  console.log('TESTING: ', name, '\n');
  const stdout = await exec('git tag --sort version:refname');
  console.log(stdout.toString('utf8'));
  console.log('END TEST: ', name, '\n\n');
}

async function main() {
  await test('node', execPromise);
  await test('mz', mzcp.exec);
}

main();
```

**`child_process` output**
```
TESTING:  node

v0.1.0
v0.2.1
v0.2.2
v0.2.3
v0.3.0
v0.4.0
v0.4.1
v0.5.0
v0.6.0

END TEST:  node
```

**`mz/child_process` output**
```
TESTING:  mz

[ 'v0.1.0\nv0.2.1\nv0.2.2\nv0.2.3\nv0.3.0\nv0.4.0\nv0.4.1\nv0.5.0\nv0.6.0\n',
  '' ]
END TEST:  mz
```

**Running `git tag --sort version:refname` in terminal**
```
bash-3.2$ git tag --sort version:refname
v0.1.0
v0.2.1
v0.2.2
v0.2.3
v0.3.0
v0.4.0
v0.4.1
v0.5.0
v0.6.0
```

**Environment**
node: v7.8.0
os: 10.12.4

**Comment by RyanZim** [comment]
You are using mz incorrectly. [`exec`'s callback](https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback) is called with three parameters, `err`, `stdout`, & `stderr`. Since a promise can only resolve to a single value, mz resolves to an array `[stdout, stderr]`.

Correct usage:
```js
const exec = require('mz/child_process').exec
const [stdout, stderr] = await exec('git tag --sort version:refname');
console.log(stdout.toString('utf8'));
```

Please close this issue. Thanks!

**Comment by cloverich** [comment]
My apologies, thank you for the extremely helpful response! (And great library btw!).

**Comment by damianobarbati** [comment]
@RyanZim isn't stderr (the error) thrown?

Your example:
```
const exec = require('mz/child_process').exec
const [stdout, stderr] = await exec('git tag --sort version:refname'); <== if stderr is not undefined then an exception should be thrown? thus this block should be in a try/catch block?
console.log(stdout.toString('utf8'));
```

BTW I get as result an array where stdout is the second element! Is this normal?
```
const [stderr, stdout] = await childProcess.exec(command);
console.log(stderr); //result, correct
console.log(stdout); //empty
```

**Comment by damianobarbati** [comment]
@RyanZim so we should never try/catch exec, right? The error is always the second parameter of the array returned.

**Comment by RyanZim** [comment]
@damianobarbati No, you still want `try`/`catch` in some cases. `stderr` is the `stderr` output of the child process, which can include simply warnings our other output. However, the promise will actually reject if there's an actual error.
